# For all clippy lints please visit: https://rust-lang.github.io/rust-clippy/master/
deny = [
    'clippy::all',
]

warn = [
    'clippy::pedantic',
    'clippy::restriction',
    'clippy::nursery',
    'clippy::cargo',
    'clippy::pub-without-shorthand'
]

allow = [
    'clippy::blanket_clippy_restriction_lints',
    'clippy::implicit_return',
    'clippy::self-named-module-files',
    'clippy::exhaustive-structs',
    'clippy::wildcard-imports',
    'clippy::shadow-reuse',
    'clippy::std-instead-of-core',
    'clippy::std-instead-of-alloc',
    'clippy::missing-trait-methods',
    'clippy::pub-use',
    'clippy::single-match-else',
    'clippy::separated-literal-suffix',
    'clippy::semicolon-outside-block',
    'clippy::question-mark-used',
    'clippy::unreachable',
    'clippy::exhaustive-enums',
    'clippy::partial-pub-fields',
    'clippy::semicolon-if-nothing-returned',
    'clippy::missing-inline-in-public-items',
    'clippy::pub-with-shorthand',
    'clippy::absolute-paths',
    'clippy::min-ident-chars',
    'clippy::error-impl-error',
    'clippy::single-call-fn',
    'clippy::multiple-unsafe-ops-per-block', # Triggers on `await`

    # Triggered by dependencies so I can't really do anything with that
    'clippy::multiple-crate-versions',
]
