# For all clippy lints please visit: https://rust-lang.github.io/rust-clippy/master/
deny = [
    'clippy::all',
]

warn = [
    'clippy::pedantic',
    'clippy::restriction',
    'clippy::nursery',
    'clippy::cargo'
]

allow = [
    'clippy::blanket_clippy_restriction_lints',
    'clippy::implicit_return',
    'clippy::self-named-module-files',
    'clippy::exhaustive-structs',
    'clippy::wildcard-imports',
    'clippy::shadow-reuse',
    'clippy::std-instead-of-core',
    'clippy::missing-trait-methods',
]
