# Usage: WEB_APP_TLS_CERTIFICATE=/path/to/cert.pem WEB_APP_TLS_KEY=/path/to/key.pem docker compose up

version: '3.9'

services:
  web_app:
    image: arjentix/telepass_web_app
    ports:
      - 80:80
      - 443:443
