# Static Web Server config file
# https://static-web-server.net/

[general]
port = 443


[advanced]

### URL Redirects

[[advanced.redirects]]
source = "**/{*}"
destination = "http://localhost:8081/$1"
kind = 301
