[package]
name = "telepass_data_model"
version = "0.1.0"
edition = "2021"
description = "Telepass data model"
authors = ["Daniil Polyakov <arjentix@gmail.com>"]
license = "MIT"
repository = "https://github.com/arjentix/telepass"
readme = "README.md"

[dependencies]
