# Usage: `docker compose up`
version: '3.9'

services:
  password_storage:
    image: arjentix/telepass_password_storage
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 50051:50051
    environment:
      DATABASE_URL: postgres://postgres:password@db/telepass_passwords
      RUST_LOG: ${RUST_LOG:-info}
      PASSWORD_STORAGE_CACHE_SIZE: ${PASSWORD_STORAGE_CACHE_SIZE:-1024}
      PASSWORD_STORAGE_TLS_CERT_PATH: /etc/password_storage/password_storage.crt
      PASSWORD_STORAGE_TLS_KEY_PATH: /etc/password_storage/password_storage.key
      ROOT_CA_CERT_PATH: /etc/password_storage/root_ca.crt

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telepass_passwords
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "telepass_passwords"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
