name: Install protoc
description: Installs protoc in the environment
runs:
    using: "composite"
    steps:
        - name: Install protoc
          run: |
            sudo apt-get update
            sudo apt-get install -y protobuf-compiler
          shell: bash
