name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [password_storage, telegram_gate, web_app]
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/telepass_${{ matrix.service }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/telepass_${{ matrix.service }}:latest
          cache-to: type=inline

  host_deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd telepass
            git checkout main
            docker compose down -rmi
            git fetch origin main
            git reset --hard origin/main
            docker compose pull
            docker compose up -d
