name: on-push

on: [push]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-06-04
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly-2023-06-04
          command: fmt
          args: --check

  doc:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: '-D warnings'
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-06-04
          components: rust-docs
      - uses: ./.github/actions/install-protoc
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly-2023-06-04
          command: doc
          args: --no-deps

  lint-workspace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-06-04
          components: clippy
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-lints
          version: latest
      - uses: ./.github/actions/install-protoc
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly-2023-06-04
          command: lints
          args: clippy --workspace --all-features

  lint-workspace-tests-benches-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-06-04
          components: clippy
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-lints
          version: latest
      - uses: ./.github/actions/install-protoc
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly-2023-06-04
          command: lints
          args: clippy --workspace --benches --tests --examples --all-features

  build-libs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-06-04
      - uses: ./.github/actions/install-protoc
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly-2023-06-04
          command: build
          args: --lib

  build-password-storage-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-06-04
      - uses: ./.github/actions/install-protoc
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly-2023-06-04
          command: build
          args: --bin telepass_password_storage

  build-telegram-gate-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-06-04
      - uses: ./.github/actions/install-protoc
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly-2023-06-04
          command: build
          args: --bin telepass_password_storage --features executable

  test-default-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-06-04
      - uses: ./.github/actions/install-protoc
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly-2023-06-04
          command: test
          args: --workspace --benches --examples

  test-development-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-06-04
      - uses: ./.github/actions/install-protoc
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly-2023-06-04
          command: test
          args: --no-default-features --features development --workspace --benches --examples

  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v3
        with:
          strict: true
          check_dot_files: true
