name: on-push

on: [push]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

  doc:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: '-D warnings'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-protoc
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps

  lint-workspace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-protoc
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --all-features

  lint-workspace-tests-benches-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-protoc
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --benches --tests --examples --all-features

  build-libs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-protoc
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --lib

  build-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-protoc
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bins --features executable

  test-default-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-protoc
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --benches --examples

  test-development-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-protoc
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --features development --workspace --benches --examples

  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v3
        with:
          strict: true
          check_dot_files: true
