[package]
name = "telepass_telegram_gate"
description = "Telegram Gateway for Telepass"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["telepass", "telegram"]
categories = ["gateway"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
dotenvy.workspace = true
color-eyre.workspace = true
thiserror.workspace = true

teloxide = "0.12.2"
