# Used in parent docker-compose.yml

version: '3.9'

services:
  telegram_gate:
    depends_on:
      password_storage:
        condition: service_healthy
    environment:
      - PASSWORD_STORAGE_URL=https://password_storage:50051
