# Usage: `TELOXIDE_TOKEN=123456789:blablabla WEB_APP_URL=https://web.app docker compose up`

version: '3.9'

services:
  telegram_gate:
    build:
      context: ..
      dockerfile: telegram_gate/Dockerfile
    environment:
      TELOXIDE_TOKEN: ${TELOXIDE_TOKEN}
      RUST_LOG: info
      PASSWORD_STORAGE_URL: https://host.docker.internal:50051
      WEB_APP_URL: ${WEB_APP_URL}
    volumes:
      - ../certs:/usr/src/telepass/certs
